In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])

In [3]:
np.shape(a)

(2, 3)

In [4]:
b = 3*a

In [5]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 3  6  9]
 [12 15 18]]


In [6]:
print(np.concatenate((a,b),axis=1))
print(np.concatenate((a,b),axis=0))

[[ 1  2  3  3  6  9]
 [ 4  5  6 12 15 18]]
[[ 1  2  3]
 [ 4  5  6]
 [ 3  6  9]
 [12 15 18]]


In [7]:
print(np.concatenate([a,b,b], axis=0))

[[ 1  2  3]
 [ 4  5  6]
 [ 3  6  9]
 [12 15 18]
 [ 3  6  9]
 [12 15 18]]


In [8]:
print(zip(a,b))

In [1]:
%reload_ext autoreload
%autoreload 2
from util.logUtil import LOG
LOG('boe')

In [2]:
LOG('bah')

In [3]:
from util.logUtil import initLogging
initLogging()
LOG('huh')

In [4]:

initLogging()
LOG('nieuw nieuw')

In [5]:
LOG('harrejakkes')

In [6]:
LOG('hus')

In [7]:
LOG('kanariepiet!')

In [8]:
%%capture tekst
for i in range(10):
    LOG('nummerr {:d}'.format(i))
    print(i)

In [9]:
tekst.show()

0
1
2
3
4
5
6
7
8
9
